# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
 - master

jobs:
- job: Testing
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-dependencies.yml
  - script: |
        pip install pytest pytest-azurepipelines pytest-cov
        python -m pytest tests/ --cov mathematics --cov-report html
    displayName: 'pytest'

- job: Linting
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-dependencies.yml
  - script: |
      pip install pylint
      python -m pylint --output-format=json --reports=y mathematics > pylint.json
    displayName: 'pylint'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'pylint'
      targetPath: 'pylint.json'

- job: Documentation
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-dependencies.yml
  - script: |
      pip install --upgrade sphinx
      sphinx-apidoc --full -a -H $TeamProject -A "$AUTHOR" -V "$SourceBranchName" -R "$SourceBranchName.$BuildID" -o "docs" "src"
      echo 'extensions.append("sphinx.ext.mathjax")' >> docs/conf.py
      echo 'mathjax_path="MathJax/MathJax.js?config=TeX-MML-AM_CHTML"' >> docs/conf.py
      mkdir docs/_static
      git clone --depth 1 --branch master https://github.com/mathjax/MathJax.git docs/_static/MathJax
      make html
    displayName: 'sphinx'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'docs'
      targetPath: 'docs'